version: "3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 1111:1111
    depends_on:
      - service1
      - service2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  service1:
    build: ./Service1
    restart: unless-stopped
    depends_on:
      - service2
    volumes:
      - /home/kazimuktadir/Desktop/BSSE1111/my_file.txt:/usr/src/app/my_file.txt

  service2:
    build: ./Service2
    restart: unless-stopped
    