POST  http://localhost:3000/api/users
Content-Type: application/json

{
    "firstname" : "abdul",
    "Llastname" : "bari",
    "email" : "kayse@gmail.com",
    "password" : "something"
    
}

###

GET http://localhost:3000/api/users
Content-Type: application/json