POST  http://localhost:3001/api/users
Content-Type: application/json

{
    "firstName" : "Fahim",
    "lastName" : "Morshed",
    "email" : "bsse1102@iit.du.ac.bd",
    "password" : "//Temujin007//"
    
}

###

GET http://localhost:3001/api/users
Content-Type: application/json

###

POST http://localhost:3001/api/auth
Content-Type: application/json

{
    "email" : "bsse1102@iit.du.ac.bd",
    "password" : "//Temujin007//"
}

###

POST http://localhost:3001/api/post
Content-Type: application/json

{
    "message": "ami ghumaitasi",
    "date": "18th Jul 2022",
    "jwtToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkZhaGltIE1vcnNoZWQiLCJpYXQiOjE2NTgxMjQxMDAsImV4cCI6MTY1ODcyODkwMH0.bGzwQgEO0_Y6-JbN5vsADjWF0pYsGJ4k160m9pEG71Q"
}

###

GET http://localhost:3001/api/post
Content-Type: application/json

###

POST http://localhost:3001/api/post/image
Content-Type: application/json

{
    "fileName": "test-from-fahim.jpg",
    "filePath": "/home/kazimuktadir/Downloads/img_snowtops.jpg",
    "metaData": {
        "Content-Type": "application/octet-stream",
        "X-Amz-Meta-Testing": 1234,
        "example": 5678,
        "username": "fahim-iit"
    }
}

###